git submodule add https://github.com/Hackerpilot/DCD.git
git submodule add https://github.com/msgpack/msgpack-d.git
git submodule add https://github.com/dscience-developers/dscience.git
git submodule add https://github.com/adamdruppe/misc-stuff-including-D-programming-language-web-stuff.git
git submodule add https://github.com/kyllingstad/scid.git
git submodule add https://github.com/WebDrake/Dgraph.git
git submodule add https://github.com/WebDrake/Rational.git
git submodule add https://github.com/PhilippeSigaud/Pegged.git
git submodule add https://bitbucket.org/denis-sh/unstandard.git
git submodule add https://github.com/linkrope/dunit.git
git submodule add https://github.com/phobos-x/phobosx.git
git submodule add https://github.com/andralex/phobos.git
git submodule add https://github.com/evilrat666/directx-d.git
git submodule add https://github.com/msoucy/dproto.git
git submodule add https://github.com/jostly/specd.git
git submodule add https://github.com/yazd/backtrace-d.git
git submodule add https://github.com/adamdruppe/misc-stuff-including-D-programming-language-web-stuff.git
git submodule add https://github.com/atilaneves/unit-threaded.git
git submodule add https://github.com/AndrejMitrovic/dchip.git
git submodule add https://github.com/atilaneves/cerealed.git
git submodule add https://github.com/atilaneves/genomed.git
git submodule add https://github.com/nordlow/msgpack-d.git
git submodule add https://github.com/9il/SIMD-Math.git
git submodule add https://github.com/DerelictOrg/DerelictGL3.git
git submodule add https://github.com/DerelictOrg/DerelictGLFW3.git
git submodule add https://github.com/DerelictOrg/DerelictFT.git
git submodule add https://github.com/DerelictOrg/DerelictFI.git
git submodule add https://github.com/DerelictOrg/DerelictUtil.git
git submodule add https://github.com/Dav1dde/glamour.git
git submodule add https://github.com/DerelictOrg/DerelictSDL2.git
git submodule add https://github.com/adamdruppe/terminal-emulator.git
git submodule add https://github.com/p0nce/gfm.git
git submodule add https://github.com/s-ludwig/dlibgit.git
git submodule add https://github.com/dymk/temple.git
git submodule add https://github.com/chadjoan/xdc.git
git submodule add https://github.com/rikkimax/Cmsed.git
git submodule add https://github.com/britseye/compo.git
git submodule add https://github.com/k3kaimu/dranges.git
git submodule add https://github.com/gpoore/minted.git
git submodule add https://github.com/dsimcha/parallel_algorithm.git
git submodule add https://github.com/Abscissa/scriptlike.git
git submodule add https://github.com/kyllingstad/zmqd.git
git submodule add https://github.com/nordlow/phobos.git
git submodule add https://github.com/aldacron/Derelict3.git
git submodule add https://github.com/DerelictOrg/DerelictIL.git
git submodule add https://github.com/DerelictOrg/DerelictOgg.git
git submodule add https://github.com/DerelictOrg/DerelictPQ.git
git submodule add https://github.com/DerelictOrg/DerelictVorbis.git
git submodule add https://github.com/DerelictOrg/DerelictSFML2.git
git submodule add https://github.com/Dgame/Dgame.git
git submodule add https://github.com/Hackerpilot/lexer-demo.git
git submodule add https://github.com/s-ludwig/libgit2.git
git submodule add https://github.com/Dav1dde/glad.git

