#!/usr/bin/env bash

if type ddemangle &> /dev/null; then
    exec rdmd -L--export-dynamic -color=on -g -gs -debug -unittest --main "$@" 2> >( ddemangle )
else
    exec rdmd -L--export-dynamic -color=on -g -gs -debug -unittest --main "$@"
fi
