#!/usr/bin/env bash

if type ddemangle &> /dev/null; then
    exec rdmd -L--export-dynamic -color=on -g -gs -debug -unittest $* 2>&1 | ddemangle
else
    exec rdmd -L--export-dynamic -color=on -g -gs -debug -unittest $* 2>&1
fi
